### PR TITLE
Separate tiles

### PR DESCRIPTION
**Pull request by Mirzipan**
Split fields and tiles into separate pages.

### CODE REVIEW

**Comment by Mirzipan** [comment]
po4a commit

**Comment by qwrtln** [comment]
po4a commit <- to see what happens when I do it

**Comment by Mirzipan** [comment]
po4a commit <- here we go again ...

**Comment by Mirzipan** [comment]
po4a commit <- one more time

**Comment by Mirzipan** [comment]
merged manually, github just doesn't recognize it.

**Pull request closed without merging**
